# Site settings
title: HackSourced
header-img: img/home-bg.jpg
email: hacksourced@gmail.com
copyright_name: HackSourced
description: "Source for all your technology-related information!"
baseurl: ""
url: "http://hacksourced.github.io"
twitter_username:
github_username:  hacksourced
facebook_username:
email_username:  hacksourced@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
